### PR TITLE
Be compatible with servers without fastcgi_finish_request

### LINKED ISSUE #119: Don't call fastcgi_finish_request on environments where is doesn't exists
I think we could rely on `function_exists` and just skip the call to this method if it doesn't exist (so on those environments the latency would be bit worst, but at least it would work)

### PR DESCRIPTION
**Pull request by gturri**
I don't have it on my personal server (I'm not sure how to get it btw)
but I noticed that with this simple patch it works fine

This fixes #119

### CODE REVIEW

**Comment by vhouchouas** [comment]
With this fix, no error will occur with `mod_php` indeed :) 
However, as we have 3 seconds to answer ([doc](https://api.slack.com/interactivity/handling)), with `mod_php` we will still have a timeout (at least that's what I have experienced).
By the way, we have another call on line 295.

**Comment by vhouchouas** [comment]
So I am not sure that we will be "compatible with servers without fastcdifinish_request".
It won't crash, but it won't work.

**Comment by gturri** [comment]
Thanks for this information.

About the limit of 3 seconds: I've tested it on a personal server (which is a small fanless, not something powerful at all) and this limit doesn't seem to be such an issue because I observe that when I register or unregister to an event, the processing takes between 1.5 seconds and 2s.
Perhaps it's because we had some perfs improvement since the moment when you experienced this issue (in particular the migration to the sql backend?)

However I have a calendar with almost no event in it, and the call to `Agenda::updateAttendee` which may end up calling `Agenda::updateEvents` will take more time as there are more events in the calendar, so perhaps this should also skip this call to `updateEvents` on such environments (the db would be updated the next time the app is called anyway). I'll check if it doesn't add too much complexity to the code.

I also need to pay attention to the other call to `fastcgi_finish_request`, thanks for drawing my attention on it 👍

**Comment by gturri** [comment]
After spending more time on it, it turns out it's indeed much easier to install php-fpm

**Pull request closed without merging**
